# ============================================================================
# 13. 配置文件 config.yaml
# ============================================================================




detection:
  min_colony_area: 800
  max_colony_area: 50000
  expand_pixels: 2
  bbox_expand_ratio: 0.01
  adaptive_gradient_thresh: 20
  adaptive_expand_iters: 25
  merge_overlapping: true
  overlap_threshold: 0.4
  use_preprocessing: true
  background_filter: false
  max_background_ratio: 0.20
  edge_contact_limit: 0.5
  enable_edge_artifact_filter: true
  edge_margin_pixels: 20
  enable_multi_stage: true
  high_quality_threshold: 0.85
  supplementary_threshold: 0.5
  shape_regularity_min: 0.15
  duplicate_centroid_threshold: 15.0
  duplicate_overlap_threshold: 0.5
  enable_duplicate_merging: true
  enable_adaptive_grid: true
  sort_by_quality: true
  min_quality_score: 0.2
  min_colonies_expected: 30
  max_mapping_distance: 2.0
  supplement_score_threshold: 0.5
  edge_margin_ratio: 0.08
  cross_boundary_overlap_threshold: 0.1
  mark_cross_boundary: true
  centroid_margin: 5
  min_roundness: 0.3
  max_aspect_ratio: 3.0
  growth_inhibited_ratio: 0.30
  solidity_threshold: 0.70

sam:
  points_per_side: 64            # 每边采样点数
  pred_iou_thresh: 0.92          # IoU阈值
  stability_score_thresh: 0.95   # 稳定性分数阈值
  min_mask_region_area: 100      # 最小掩码区域面积
  crop_n_layers: 1               # 裁剪层数
  crop_n_points_downscale_factor: 1  # 下采样因子

analysis:
  advanced: true               # 是否启用高级分析
  learning_enabled: false      # 是否启用学习系统
  aerial_threshold: 0.6        # 气生菌丝阈值
  metabolite_threshold: 0.5    # 代谢产物阈值
  enable_parallel: false       # 是否启用并行处理
  max_workers: 4               # 最大工作线程数

output:
  debug: true                   # 是否生成调试输出
  well_plate: false             # 是否使用孔板编号
  rows: 8                       # 孔板行数
  cols: 12                      # 孔板列数
  save_masks: true              # 是否保存掩码
  save_visualizations: true     # 是否保存可视化
  image_format: jpg             # 图像输出格式

logging:
  level: DEBUG                  # 日志级别: DEBUG, INFO, WARNING, ERROR
  log_to_file: true             # 是否记录到文件
  log_dir: null                 # 日志目录 (null = 自动)
  max_log_files: 10             # 最大日志文件数

# 媒介特定的参数覆盖
medium_params:
  r5:
    sam:
      pred_iou_thresh: 0.90
      stability_score_thresh: 0.80
    detection:
      min_colony_area: 600
  mm:
    sam:
      pred_iou_thresh: 0.80
      stability_score_thresh: 0.65
    detection:
      min_colony_area: 400
    back:
      detection:
        background_filter: false
        adaptive_gradient_thresh: 15
        duplicate_overlap_threshold: 0.7  # 更严格的重复判定
